spring.application.name=mtc
#https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
spring.jpa.open-in-view=false
# server
server.port=8080
# Data Source Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
# JPA / Hibernate Configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=public
# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.example.bank=DEBUG
# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379